### ISSUE TITLE
Case Study 5 Notes

### ISSUE THREAD

**Issue by haleighborich** [DTS350Fall2021/MorrillL#9]
Used a reorder for the seasons
Created good graphics for the Gun Deaths
Most people killed had only a high school diploma / GED
A lot of deaths spiked in the Summer season
Majority of people killed were white
The majority of deaths were in the age range 15-64
Majority of people killed were male
Male suicide spikes once age increases
Female homicide stayed consistent through age groups

Was the education level surprising to figure out?
When looking at the scale on the y axis, for Logan's 4th graph, it is surprising to see how different each race is when comparing. 

I think Logan address all of the question for the client and gave them good answers to start their commercial.

**Comment by logan1m** [comment]
Thank you for the feedback
